# Generated by Django 3.1.7 on 2021-04-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('edition', models.CharField(max_length=40)),
                ('condition', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn', models.IntegerField()),
            ],
        ),
    ]
