# Generated by Django 3.1.7 on 2021-04-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210422_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
    ]
