# Generated by Django 3.1.7 on 2021-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='createdBy',
            field=models.CharField(default='none', editable=False, max_length=40),
        ),
    ]
