# Generated by Django 3.1.7 on 2021-04-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_book_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createdBy',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.book')),
            ],
        ),
    ]
