# Generated by Django 3.2 on 2021-05-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210428_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_searches', models.IntegerField(default=0)),
            ],
        ),
    ]
