# Generated by Django 3.2 on 2021-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_totalsearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='', max_length=100),
        ),
    ]
