# Generated by Django 3.2 on 2021-05-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('createdBy', models.CharField(max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
