# Generated by Django 3.2 on 2021-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookId',
            field=models.CharField(default=10, max_length=40),
        ),
    ]
