# Generated by Django 3.2 on 2021-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210504_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.UUIDField(default='djh2xgKG2AeJ3CpwAA3QxJ', editable=False, primary_key=True, serialize=False),
        ),
    ]
