# Generated by Django 3.2 on 2021-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='7ibcNLE8iCY6aBQZBPWub3', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
