# Generated by Django 3.2 on 2021-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_book_bookid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=40)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='PJPSrQMfSibpT6B5iMVcPk', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
