# Generated by Django 3.2 on 2021-05-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210509_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('createdBy', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='EFjDnXFkVHjXWQ57BkP6JS', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reports',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.book'),
        ),
    ]
