# Generated by Django 3.1.7 on 2021-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210509_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='DurSjTZbWag3FfKobKmaRJ', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
