# Generated by Django 3.2.1 on 2021-05-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210509_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='8zVNg7cEmAZHrFaK7xjHkZ', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
