# Generated by Django 3.2 on 2021-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210510_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='dV3JKjqP8HGeKzBjKYLnGn', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
