# Generated by Django 3.1.7 on 2021-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210510_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buyer_rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='major2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='4pAmLjZH3wAnahguceSX28', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
