# Generated by Django 3.2.1 on 2021-05-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210510_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBooksCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='K8XGVCoh5RghtBnQjEcHTZ', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
