# Generated by Django 3.2 on 2021-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210510_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalBooksCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='bookId',
            new_name='bookName',
        ),
        migrations.AddField(
            model_name='profile',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='5D2yn6sfGMh6NQXrk329Pn', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
