# Generated by Django 3.2 on 2021-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210511_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sellerLink',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='2TMKqy4JwnkEnMXVv29n7b', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
