# Generated by Django 3.2 on 2021-05-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210510_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buyer_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='QuUwUFBf2zLJuVnuCAxMGN', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
