# Generated by Django 3.2 on 2021-05-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210510_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='buyer_avg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seller_avg',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='2bjXWFihr5Skues3htqp6G', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
