# Generated by Django 3.2 on 2021-05-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='JKRTa37MPqcxF7oF3jVHTs', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
