# Generated by Django 3.2 on 2021-05-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210510_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold',
            old_name='bookId',
            new_name='bookName',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='HWM7Xw5pBTiQ4Uborgh644', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
