# Generated by Django 3.2 on 2021-05-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210510_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='fouuWHa8ksKzp4xoyBgREr', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
