# Generated by Django 3.2.1 on 2021-05-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_book_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'Buyer'), (2, 'Seller')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='ajwkNnVAchdCf9vWXihHG5', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
