# Generated by Django 3.2.1 on 2021-05-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210512_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ratings',
            new_name='buyer_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='DQAPnvTFBVMHL2evy2qSKh', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
