# Generated by Django 3.2.1 on 2021-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_book_bookid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ratings',
            new_name='buyer_count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='message',
        ),
        migrations.AddField(
            model_name='profile',
            name='average_buyer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='average_seller',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'Buyer'), (2, 'Seller')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='Qv4bKauqQJZ4QR46XQsr2D', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
