# Generated by Django 3.2.1 on 2021-05-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210512_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default=0, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
