# Generated by Django 3.2.1 on 2021-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210512_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='message',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='99WcWkhi3eAgNUezX6hXFo', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
