# Generated by Django 3.2.1 on 2021-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210512_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_buyer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='average_seller',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(default='RKUx68g3nEoaGPTy4W6uJn', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
